### ISSUE TITLE
Azure Pipeline Timeout

### ISSUE THREAD

**Issue by joshcampbell191** [joshcampbell191/EBG.Xrm.AzureDevOpsTasks#1]
@pathartl 

I opened a bug to further track your timeout [issue](https://twitter.com/pathartl/status/1478512617555697665?s=21). I'll see about putting together a sample YAML pipeline.

**Comment by joshcampbell191** [comment]
Here's a YAML sample of the pipeline tasks:

```
pool:
  name: Azure Pipelines
  demands: powershell

variables:
  crm.url: 'https://org#######.crm#.dynamics.com/'
  tenant.appId: '########-####-####-####-############'
  tenant.secret: '**************************'

steps:
- task: JoshuaCampbell.ebg-devops-tools.EBGToolInstaller.EBGToolInstaller@1
  displayName: 'EBG DevOps Tool Installer'
  inputs:
    ebgApiVersion: latest

- task: JoshuaCampbell.ebg-devops-tools.EBGEarlyBoundGenerator.EBGEarlyBoundGenerator@1
  displayName: 'Early Bound Generator'
  inputs:
    crmConnectionString: 'AuthType=ClientSecret;Url=$(crm.url);ClientId=$(tenant.appId);ClientSecret=$(tenant.secret)'
    settingsPath: DLaB.EarlyBoundGenerator.DefaultSettings.xml
```

Please note that this only installs the EBG tools (latest version) and exports them according to the [DLaB.EarlyBoundGenerator.DefaultSettings.xml](https://github.com/joshcampbell191/EBG.Xrm.AzureDevOpsTasks/files/7823360/DLaB.EarlyBoundGenerator.DefaultSettings.xml.txt) settings file.

**Comment by joshcampbell191** [comment]
The pipeline tasks have been updated to include the logs generated by the Early Bound Generator. 

In order to view the logs, please ensure you run with the following settings:

```
pool:
  name: Azure Pipelines
  demands: powershell

variables:
  crm.url: 'https://org#######.crm#.dynamics.com/'
  tenant.appId: '########-####-####-####-############'
  tenant.secret: '**************************'

steps:
- task: JoshuaCampbell.ebg-devops-tools-preview.EBGToolInstaller.EBGToolInstaller@1
  displayName: 'EBG DevOps Tool Installer'
  inputs:
    ebgApiVersion: latest

- task: JoshuaCampbell.ebg-devops-tools-preview.EBGEarlyBoundGenerator.EBGEarlyBoundGenerator@1
  displayName: 'Early Bound Generator'
  inputs:
    crmConnectionString: 'AuthType=ClientSecret;Url=$(crm.url);ClientId=$(tenant.appId);ClientSecret=$(tenant.secret)'
    settingsPath: DLaB.EarlyBoundGenerator.DefaultSettings.xml
```

 `Execute Async` should be set to `false` and `Enable system diagnostics` should be set to true (or `system.debug`).

![image](https://user-images.githubusercontent.com/1784236/148609758-a11807a4-2903-4141-82ab-6f281bbd7821.png)

**Comment by pathartl** [comment]
Wonderful! I was able to get the task running without timeout. I believe I did not specify `settingsPath` and might have been hanging the task. I was not able to get it fully integrated into our pipeline because of the lack of logging, but I will give it another shot. Thanks for the addition!

**Comment by pathartl** [comment]
I've got this fully implemented in our pipeline now, thank you for your help! Here's my full yaml:

```yaml
pool:
  vmImage: windows-latest

variables:
  system.debug: true

steps:
- checkout: self
  persistCredentials: true

- task: EBGToolInstaller@1
  inputs:
    nugetFeed: 'official'
    ebgApiVersion: latest

- task: MSCRMToolInstaller@12
  inputs:
    nugetFeed: 'official'
    psFeed: 'official'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: '00000000-0000-0000-0000-000000000000'

- task: DeleteFiles@1
  inputs:
    SourceFolder: 'Entities'
    Contents: '**/*.cs'
    RemoveSourceFolder: true

- task: DeleteFiles@1
  inputs:
    SourceFolder: 'Actions'
    Contents: '**/*.cs'
    RemoveSourceFolder: true

- task: DeleteFiles@1
  inputs:
    SourceFolder: 'OptionSets'
    Contents: '**/*.cs'
    RemoveSourceFolder: true

- task: MSCRMPublishCustomizations@12
  inputs:
    crmConnectionString: 'AuthType=OAuth;Username=$(Username);Password=$(Password);Url=$(Url);AppId=51f81489-12ee-4a9e-aaae-a2591f45987d;RedirectUri=app://58145B91-0C36-4500-8554-080854F2AC97;LoginPrompt=Never'

- task: EBGEarlyBoundGenerator@1
  inputs:
    crmConnectionString: 'AuthType=OAuth;Username=$(Username);Password=$(Password);Url=$(Url);AppId=51f81489-12ee-4a9e-aaae-a2591f45987d;RedirectUri=app://58145B91-0C36-4500-8554-080854F2AC97;LoginPrompt=Never'
    settingsPath: 'DLaB.EarlyBoundGenerator.Settings.xml'

- task: MSCRMGetSolution@12
  inputs:
    crmConnectionString: 'AuthType=OAuth;Username=$(Username);Password=$(Password);Url=$(Url);AppId=51f81489-12ee-4a9e-aaae-a2591f45987d;RedirectUri=app://58145B91-0C36-4500-8554-080854F2AC97;LoginPrompt=Never'
    solutionName: '$(SolutionName)'
    versionVariableName: 'SolutionVersion'
    displayVariableName: 'SolutionDisplayName'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $version="${env:SOLUTIONVERSION}"
      $date=$(Get-Date -UFormat "%Y%m%d%H%M");
      Write-Host "##vso[task.setvariable variable=SOLUTIONVERSION]$version-$date"

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      git config --global user.email "user@example.com"
      git config --global user.name "John Doe"

      Write-Host "GIT SHOW REF"
      git remote update
      git fetch 
      git show-ref

      Write-Host "GIT CHECKOUT MASTER"
      git checkout --track origin/master

      Write-Host "GIT STATUS"
      git status

      Write-Host "GIT ADD"
      git add -A

      Write-Host "GIT COMMIT"
      git commit -a -m "Update of proxy classes to version ${env:SOLUTIONVERSION}"

      Write-Host "GIT TAG"
      git tag -a "v${env:SOLUTIONVERSION}" -m "Version ${env:SOLUTIONVERSION}"

      Write-Host "GIT STATUS"
      git status

      Write-Host "GIT PUSH"
      git push origin
      git push --tags origin

      Write-Host "GIT STATUS"
      git status

- task: MSBuild@1
  inputs:
    solution: '**/*.sln'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'SolutionVersion'
    includeSymbols: true

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '00000000-0000-0000-0000-000000000000'
```

This config:
* Clears out the `Entities`, `Actions`, and `OptionSets` folders in the git repository
* Publishes all customizations
* Runs EBG to create a file for each entity, action, and option set in their respective folders (defined in xml)
* Gets the solution version and defines a build version of  `$(SolutionVersion)-yyyymmddHHMM`
* Commits all the changes to master
* Builds the solution
* Packs and pushes as a package to our private NuGet feed

We rely on EBG pretty heavily for things like Azure Functions and migration utilities, so it's nice to be able to have it accessible right in NuGet.
